# Name : MITTA SAI NITISH
# Reg No : 20MID0054
# College : VIT Vellore
## EMAIL : mittasai.nitish2020@vitstudent.ac.in
#                                          -------AI Assignment 1---------

### Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(42)

# Create random values
data = np.random.rand(4, 4)

In [2]:
print(data)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]


In [3]:
# Create the DataFrame
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
print(df)

   Feature1  Feature2  Feature3  Feature4
0  0.374540  0.950714  0.731994  0.598658
1  0.156019  0.155995  0.058084  0.866176
2  0.601115  0.708073  0.020584  0.969910
3  0.832443  0.212339  0.181825  0.183405


### Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4

In [4]:
# Rename the column names
df.rename(columns={'Feature1': 'Random value 1', 'Feature2': 'Random value 2',
                   'Feature3': 'Random value 3', 'Feature4': 'Random value 4'},
          inplace=True)
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.374540        0.950714        0.731994        0.598658
1        0.156019        0.155995        0.058084        0.866176
2        0.601115        0.708073        0.020584        0.969910
3        0.832443        0.212339        0.181825        0.183405


### Find the descriptive statistics of the 'df' dataframe.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes


In [6]:
# Display descriptive statistics
df.describe(include='all')

Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.491029        0.506780        0.248122        0.654537
std          0.291252        0.386153        0.329856        0.350875
min          0.156019        0.155995        0.020584        0.183405
25%          0.319910        0.198253        0.048709        0.494845
50%          0.487828        0.460206        0.119954        0.732417
75%          0.658947        0.768733        0.319367        0.892110
max          0.832443        0.950714        0.731994        0.969910

### Check for the null values in 'df' and find the data type of the columns

In [7]:
# Check for null values
null_values = df.isnull().sum()

# Print null values
print("Null Values:\n", null_values)

# Find data types of columns
data_types = df.dtypes

# Print data types
print("\nData Types:\n", data_types)


Null Values:
 Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

Data Types:
 Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object


### Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [8]:
# Display columns using location method
location_method_cols = df.loc[:, ['Random value 2', 'Random value 3']]
print("Columns using location method:\n", location_method_cols)

# Display columns using index location method
index_location_method_cols = df.iloc[:, [1, 2]]
print("\nColumns using index location method:\n", index_location_method_cols)


Columns using location method:
    Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825

Columns using index location method:
    Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825
